name: Package Unit Tests

on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: pip install -r requirements.txt coverage
    - name: Run unit tests
      run: coverage run -m unittest discover
    - name: run coverage report
      run: coverage report --include=scripts/* --skip-covered -m